# Generated by Django 3.2.6 on 2022-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmconso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='hour_begin',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='rule',
            name='hour_end',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
